### ISSUE TITLE
Error in search

### ISSUE THREAD

**Issue by GryptpypeThynne** [SMAPPNYU/youtube-data-api#17]
On python 3.7.3 using search returns 
`File "C:\Program Files\Python37\lib\site-packages\youtube_api\youtube_api.py", line 740, in search
    if len(videos) >= max_results:
TypeError: '>=' not supported between instances of 'int' and 'str' `

**Comment by GryptpypeThynne** [comment]
Should have said: this occurs if someone doesn't use int() to set max_results

**Comment by yinleon** [comment]
Hi @GryptpypeThynne that parameter should only be an int. If I'm understanding you you hit an error when you used a string for `max_results`?

**Comment by GryptpypeThynne** [comment]
That's right yeah. I only came across the error when using input() to get `max_results`. I realize that in most cases the input would be sanitized with int(), but I just figured that that could be better done in the actual package, just in to eliminate the error case.

**Comment by yinleon** [comment]
Maybe we can make explicit dtypes for each argument. I think it makes the source code look super weird, but it might be better to change this up. I'll make a new issue for this, thanks @GryptpypeThynne
