### ISSUE TITLE
get_video_metadata() fails with error about missing statistics key

### ISSUE THREAD

**Issue by cbuntain** [SMAPPNYU/youtube-data-api#19]
**Describe the bug**
In the current implementation of `get_video_metadata()`, the function fails for me with default parameters. The error is related to a missing `statistics` key in the parsed JSON result. While I think I can track this issue to the default parser used in `get_video_metadata()`, even if I provide "statistics" as part of the requested data parts, the error persists.

**Expected behavior**
In the default behavior, this function should return video metadata that includes both `statistics` and `snippet` data. The parser should work with this default data.

**Desktop (please complete the following information):**
 - OS: Unix-compatible

**Comment by yinleon** [comment]
Hey @mabrownnyu, did you resolve this?

**Comment by mattm401** [comment]
Similarly bumping into this issue.

**Comment by yinleon** [comment]
Should work now: https://github.com/SMAPPNYU/youtube-data-api/blob/master/youtube_api/youtube_api.py#L251
