### ISSUE TITLE
Tests needed

### ISSUE THREAD

**Issue by yinleon** [SMAPPNYU/youtube-data-api#3]
Hi we need a test for:

- [ ] search

- [x] get_captions

- [ ] get_playlists

- [x] get_videos_from_playlist

- [ ] get_subscriptions

- [ ] get_featured_channels

- [ ] get_video_captions

- [ ] get_recommended_videos

Search has a lot of arguments, and get_captions does not use the API!

**Comment by yinleon** [comment]
This is a topic that needs revisiting. 
Thanks to @Michael98Liu for writing up how tests and travis work.

The current tests are incomplete or don't cover enough of the functions.
For example, [test_video_methods](https://github.com/SMAPPNYU/youtube-data-api/blob/master/tests/test_video_methods.py) does not actually test anything.
Also need to figure out whose key is being used in Travis.

**Comment by mabrownnyu** [comment]
Closed because replaced with #16
