### ISSUE TITLE
Error in get_videos_from_playlist_id

### ISSUE THREAD

**Issue by kmunger** [SMAPPNYU/youtube-data-api#33]
I'm re-running code that worked in the spring of 2019. 

Most of the functions work fine but I'm having issues with the one listed above. When I call

yt.get_videos_from_playlist_id("UUaeO5vkdj5xOQHp4UmIN6dw")

I get the following message.

TypeError                                 Traceback (most recent call last)
<ipython-input-25-16d50b680f65> in <module>()
----> 1 yt.get_videos_from_playlist_id("UUaeO5vkdj5xOQHp4UmIN6dw")

C:\Users\kevin\Anaconda3\lib\site-packages\youtube_api\youtube_api.py in get_videos_from_playlist_id(self, playlist_id, next_page_token, published_after, parser)
    265                 for item in response_json.get('items'):
    266                     publish_date = parse_yt_datetime(item['snippet'].get('publishedAt'))
--> 267                     if publish_date <= published_after:
    268                         run=False
    269                         break

TypeError: '<=' not supported between instances of 'NoneType' and 'datetime.datetime'

**Comment by mabrownnyu** [comment]
Error fixed and published in the most recent version on pypi
