### ISSUE TITLE
Documents typo

### ISSUE THREAD

**Issue by gemini-mouse** [SMAPPNYU/youtube-data-api#40]
Hi, there is an error in the documents as follows

https://youtube-data-api.readthedocs.io/en/latest/usage/quickstart.html

import os
import pandas as pd
from youtube_api import YoutubeDataApi    <----- because import as Api

YT_KEY = os.environ.get('YOUTUBE_API_KEY') # you can hardcode this, too.
yt = YouTubeDataAPI(YT_KEY)        <-----------typo here, API shall be Api

this is a great tool, but this error might cause some beginners stuck on this stage.

thank you for your brilliant work.

**Comment by yinleon** [comment]
Hi @gemini-mouse, we currently have the class with "API" and "Api" as of v.0.0.20.
However, we are going to depreciate "Api" as we noted in the docstring.
